name: pubdev_explorer_core
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  drift: ^2.22.0
  equatable: ^2.0.7
  http: ^1.2.2
  path: ^1.9.1
  pot: ^0.7.1

dev_dependencies:
  build_runner: ^2.4.13
  drift_dev: ^2.22.0
  lints: ^5.0.0
