name: pubdev_explorer_core
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  drift: ^2.14.0
  equatable: ^2.0.5
  http: ^1.1.2
  json_annotation: ^4.8.1
  path: ^1.9.0
  pot: ^0.6.0

dev_dependencies:
  build_runner: ^2.4.7
  drift_dev: ^2.14.0
  json_serializable: ^6.7.1
  lints: ^3.0.0
