name: pubdev_explorer_core
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  drift: ^2.11.1
  equatable: ^2.0.5
  http: ^1.1.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  pot: ^0.4.2+1

dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.11.2
  json_serializable: ^6.7.1
  lints: ^2.1.1
