name: pubdev_explorer_core
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  collection: ^1.17.0
  drift: ^2.5.0
  equatable: ^2.0.5
  http: ^0.13.5
  json_annotation: ^4.8.0
  path: ^1.8.3
  pot: ^0.4.2

dev_dependencies:
  build_runner: ^2.3.3
  drift_dev: ^2.5.2
  json_serializable: ^6.6.1
  lints: ^2.0.1
