name: pubdev_explorer_domain
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  collection: ^1.17.0
  drift: ^2.2.0
  equatable: ^2.0.5
  http: ^0.13.5
  json_annotation: ^4.7.0
  path: ^1.8.2
  pot: ^0.4.1

dev_dependencies:
  build_runner: ^2.3.2
  drift_dev: ^2.2.0+1
  json_serializable: ^6.5.4
  lints: ^2.0.1
