name: pubdev_explorer
description: An app to explore and bookmark packages hosted on pub.dev.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  pubdev_explorer_core:
    path: ../core

  # Packages by the app author
  async_phase_notifier: ^0.4.1
  custom_text: ^1.1.0
  grab: ^0.4.1
  pottery: ^0.1.0

  # Other packages
  collection: ^1.18.0
  drift: ^2.13.1
  equatable: ^2.0.5
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.1
  sqlite3_flutter_libs: ^0.5.18
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_lints: ^3.0.1

  custom_lint: ^0.5.6
  grab_lints: ^0.3.2

flutter:
  uses-material-design: true
