name: pubdev_explorer
description: An app to explore and bookmark packages hosted on pub.dev.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  pubdev_explorer_core:
    path: ../core

  # Packages by the app author
  async_phase_notifier: ^0.4.1
  custom_text: ^1.3.0
  grab: ^0.4.2
  pottery: ^0.2.0

  # Other packages
  collection: ^1.18.0
  drift: ^2.14.0
  equatable: ^2.0.5
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.1
  sqlite3_flutter_libs: ^0.5.18
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_lints: ^3.0.1

  custom_lint: ^0.5.7
  grab_lints: ^0.4.0

flutter:
  uses-material-design: true
