name: pubdev_explorer
description: An app to explore and bookmark packages hosted on pub.dev.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  pubdev_explorer_core:
    path: ../core

  # Packages by the app author
  async_phase_notifier: ^0.4.2
  custom_text: ^1.4.4
  grab: ^1.0.0-dev.1
  pottery: ^0.4.2

  # Other packages
  collection: ^1.18.0
  drift: ^2.15.0
  equatable: ^2.0.5
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.2
  sqlite3_flutter_libs: ^0.5.19+1
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
