name: pubdev_explorer
description: An app to explore and bookmark packages hosted on pub.dev.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  pubdev_explorer_core:
    path: ../core

  # Packages by the app author
  async_phase_notifier: ^0.4.1
  custom_text: ^1.1.0
  grab: ^0.4.1
  pottery:
    git:
      url: https://github.com/kaboc/pot.git
      path: packages/pottery
      ref: 18cd420f932aa52fa4a057e7220ffffb20173c06

  # Other packages
  collection: ^1.17.1
  drift: ^2.11.1
  equatable: ^2.0.5
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.1
  sqlite3_flutter_libs: ^0.5.17
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_lints: ^2.0.3

  custom_lint: ^0.5.3
  grab_lints:
    git: https://github.com/kaboc/grab-lints.git

flutter:
  uses-material-design: true
